import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 960, height: 540 } });
const errs = [];
p.on('console', m => m.type() === 'error' && errs.push(m.text()));
p.on('pageerror', e => errs.push(String(e)));
await p.goto('file:///home/claude/work/claude-quest/dist/index.html');
await p.waitForTimeout(3000);
console.log('loaded');
const cv = await p.$('canvas'); const box = await cv.boundingBox();
const tap = (x, y) => p.mouse.click(box.x + box.width * x / 480, box.y + box.height * y / 270);
await tap(240, 180); await p.waitForTimeout(800); console.log('begin');
await p.screenshot({ path: '/tmp/ow_select.png' }); console.log('shot select');
await tap(150, 130); await p.waitForTimeout(900); console.log('picked');
await tap(60, 58); await p.waitForTimeout(1000); console.log('zone1');
await p.screenshot({ path: '/tmp/ow_world.png' }); console.log('shot world');
await p.keyboard.down('ArrowLeft'); await p.waitForTimeout(900); await p.keyboard.up('ArrowLeft');
await p.keyboard.down('ArrowUp'); await p.waitForTimeout(600); await p.keyboard.up('ArrowUp');
await p.screenshot({ path: '/tmp/ow_walked.png' }); console.log('walked');
await p.keyboard.press('E'); await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/ow_dialogue.png' }); console.log('dialogue');
console.log('errors:', errs.length ? errs : 'none');
await b.close();
